#!/usr/bin/env sh

ROOT_DIR=$(git rev-parse --show-toplevel)

source "$ROOT_DIR/scripts/styleText.sh"

files=$(git diff-index --cached --name-only --diff-filter=ACMR HEAD | grep -vE "bun.lock")
eslint_files=$(echo "$files" | grep -E ".*\.([jt]sx?|json|css)$" || true)

logInfo "⏳ Checking for linting errors..."
if [ -n "$eslint_files" ]; then
  bun lint $eslint_files
  logSuccess "Linter check passed!"
else
  logInfo "No files to check for linting."
fi

logInfo "⏳ Checking for formatting errors..."
if [ -n "$files" ]; then
  bun format $files
  logSuccess "Formatter check passed!"
else
  logInfo "No files to check for formatting."
fi

logInfo "⏳ Checking for checking errors..."
if [ -n "$files" ]; then
  bun check $files
  logSuccess "Check passed!"
else
  logInfo "No files to check."
fi
