#!/usr/bin/env sh

BLUE='\033[34;1m'
GREEN='\033[32;1m'
RESET='\033[m'

logBlue() {
  printf "$BLUE%s$RESET" "$@"
}

logGreen() {
  printf "$GREEN%s$RESET" "$@"
}

logFormat() {
  local text="$1"
  shift
  printf "[ $text ] %s\n" "$@"
}

logInfo() {
  logFormat "$(logBlue "INFO")" "ℹ️  $@"
}

logSuccess() {
  logFormat "$(logGreen "SUCCESS")" "✅ $@"
}

files=$(git diff-index --cached --name-only --diff-filter=ACMR HEAD | grep -vE "bun.lock")
eslint_files=$(echo "$files" | grep -E ".*\.([jt]sx?|json|css)$" || true)

logInfo "⏳ Checking for linting errors..."
if [ -n "$eslint_files" ]; then
  bun lint $eslint_files
  logSuccess "Linter check passed!"
else
  logInfo "No files to check for linting."
fi

logInfo "⏳ Checking for formatting errors..."
if [ -n "$files" ]; then
  bun format $files
  logSuccess "Formatter check passed!"
else
  logInfo "No files to check for formatting."
fi

logInfo "⏳ Checking for checking errors..."
if [ -n "$files" ]; then
  bun check $files
  logSuccess "Check passed!"
else
  logInfo "No files to check."
fi
